### ISSUE TITLE
my suggestion

### ISSUE THREAD

**Issue by og-dorit0** [Super-Glowridden/SuperGlowridden#4]
put the mmo game and the crative server in to one server or have a portal link to the othere world

**Comment by NotSoNooby** [comment]
Could you elaborate on this please?

**Comment by NotSoNooby** [comment]
right, i see that you edited your comment.

**Comment by NotSoNooby** [comment]
I could join them together with BungeeCord, but Anyname Craft is only a fallback server if Super Glowridden doesn't work or isn't up.
