### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by samodoom1** [Super-Glowridden/SuperGlowridden#6]
add a disguise plugin

**Comment by NotSoNooby** [comment]
Ok. Could you explain to me what exaclty it is that you want?

**Comment by samodoom1** [comment]
a plugin that adds /disguise

**Comment by NotSoNooby** [comment]
Ok. So something that like changes what you look like right?

**Comment by samodoom1** [comment]
yea... u can become a player, animal or mob

**Comment by NotSoNooby** [comment]
Ok. I will add that on my todo list.

**Comment by NotSoNooby** [comment]
added
